# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pushtest.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QStatusBar, QWidget)
import kari_rc
import kari_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1057, 770)
        font = QFont()
        font.setPointSize(11)
        font.setItalic(True)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton1 = QPushButton(self.centralwidget)
        self.pushButton1.setObjectName(u"pushButton1")
        self.pushButton1.setGeometry(QRect(70, 270, 95, 25))
        self.pushButton2 = QPushButton(self.centralwidget)
        self.pushButton2.setObjectName(u"pushButton2")
        self.pushButton2.setGeometry(QRect(260, 270, 95, 25))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 30, 191, 221))
        self.label.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label.setPixmap(QPixmap(u":/newPrefix/news-p.v1.202508.c90bf1d41da64297a5c5666d4a119a16_P1.webp"))
        self.label.setScaledContents(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(240, 20, 201, 221))
        self.label_2.setPixmap(QPixmap(u":/newPrefix/401452_490340_4225.jpg"))
        self.label_2.setScaledContents(True)
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(200, 360, 281, 51))
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(200, 440, 281, 71))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 360, 91, 31))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(60, 440, 101, 41))
        self.radioButton = QRadioButton(self.centralwidget)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(570, 210, 111, 22))
        self.radioButton_2 = QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(570, 240, 111, 22))
        self.radioButton_3 = QRadioButton(self.centralwidget)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(570, 270, 111, 22))
        self.radioButton_4 = QRadioButton(self.centralwidget)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(570, 300, 111, 22))
        self.radioButton_5 = QRadioButton(self.centralwidget)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(570, 330, 111, 22))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(540, 40, 171, 101))
        font1 = QFont()
        font1.setPointSize(16)
        font1.setItalic(True)
        self.label_5.setFont(font1)
        self.radioButton_6 = QRadioButton(self.centralwidget)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setGeometry(QRect(780, 210, 111, 22))
        self.radioButton_7 = QRadioButton(self.centralwidget)
        self.radioButton_7.setObjectName(u"radioButton_7")
        self.radioButton_7.setGeometry(QRect(780, 250, 111, 22))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(560, 160, 131, 231))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(770, 150, 131, 231))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(750, 70, 141, 71))
        font2 = QFont()
        font2.setPointSize(15)
        font2.setItalic(True)
        self.label_6.setFont(font2)
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(570, 400, 91, 22))
        self.checkBox_2 = QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(570, 420, 91, 22))
        self.checkBox_3 = QCheckBox(self.centralwidget)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(570, 440, 91, 22))
        self.checkBox_4 = QCheckBox(self.centralwidget)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(570, 470, 91, 22))
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(520, 10, 171, 41))
        self.comboBox_2 = QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(720, 10, 171, 41))
        self.listWidget = QListWidget(self.centralwidget)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(750, 400, 256, 192))
        MainWindow.setCentralWidget(self.centralwidget)
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.pushButton1.raise_()
        self.pushButton2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.label_5.raise_()
        self.radioButton_6.raise_()
        self.radioButton_7.raise_()
        self.label_6.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.listWidget.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1057, 27))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton1.setText(QCoreApplication.translate("MainWindow", u"on", None))
        self.pushButton2.setText(QCoreApplication.translate("MainWindow", u"off", None))
        self.label.setText("")
        self.label_2.setText("")
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"\ub4e4\uc5b4\uc640", None))
        self.lineEdit_2.setText(QCoreApplication.translate("MainWindow", u"\uc8fc\uc18c \uc785\ub825\ud574", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\uc544\uc774\ub514 \uc785\ub825", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\ube44\ubc00\ubc88\ud638 \uc785\ub825", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"RadioButton", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"RadioButton", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"\ubc84\uc12f\uc870\ub9bc", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"\uc7a5\uc870\ub9bc", None))
        self.radioButton_5.setText(QCoreApplication.translate("MainWindow", u"\uc6b0\uc2b9\uc870\ub9bc", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\uc5b4\ub5a4 \uc870\ub9bc", None))
        self.radioButton_6.setText(QCoreApplication.translate("MainWindow", u"\uc591\uc2dd", None))
        self.radioButton_7.setText(QCoreApplication.translate("MainWindow", u"\ud55c\uc2dd", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\uc5b4\ub5a4 \uc2a4\ud0c0\uc77c", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\uae40\ucc44\uc5f0", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"\uce74\ub9ac\ub098", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"CheckBox", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"CheckBox", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\ub4e4\uae30\ub984", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\ucc38\uae30\ub984", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\uace0\ucd94\uc7a5", None))

    # retranslateUi

