h="{:+5d}".format(52)
i="{:+5d}".format(-52)
j="{:=+5d}".format(52)
k="{:=+5d}".format(-52)
l="{:+05d}".format(52)
m="{:+05d}".format(-52)

print("# 조합하기")
print(h)
print(i)
print(j)
print(k)
print(l)
print(m)

a="hello python programmin"
b=a.upper()
print(b)
c=b.lower()
print(c)